name: musicio (Backend)

on:
  push:
    branches:
      - master
    paths:
      - "packages/server/**"
      - ".github/workflows/backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add backend remote origin
        run: git remote add heroku-backend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_BACKEND_APP_NAME }}.git
      - name: Deploy backend to Heroku
        run: git push heroku-backend `git subtree split --prefix packages/server master`:refs/heads/master --force
