name: musicio (Backend)

on:
  push:
    branches:
      - master
    paths:
      - "packages/server/**"
      - ".github/workflows/backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
          heroku_app_name: ${{secrets.HEROKU_BACKEND_APP_NAME}}
          heroku_email: "artemarsupial@gmail.com"
          appdir: "packages/server" # <- This will point to the api folder in your project
          remote_branch: "heroku-backend"
