name: Deploy to Heroku (Frontend)

on:
  push:
    branches:
      - master
    paths:
      - "packages/client/**"
      - ".github/workflows/frontend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{secrets.FLY_API_TOKEN}}
          appdir: "packages/client" # <- This will point to the api folder in your project
