name: Deploy to Heroku (Frontend)

on:
  push:
    branches:
      - master
    paths:
      - "packages/client/**"
      - ".github/workflows/frontend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
          heroku_app_name: ${{secrets.HEROKU_FRONTEND_APP_NAME}}
          heroku_email: "artemarsupial@gmail.com"
      - name: Add frontend remote origin
        run: git remote add heroku-frontend https://git.heroku.com/${{ secrets.HEROKU_FRONTEND_APP_NAME }}.git
      - name: Deploy frontend to Heroku
        run: git push heroku-frontend `git subtree split --prefix packages/client master`:refs/heads/main --force
